README.md
api/auth/jwt.go
api/auth/security.go
cache/keysaver/keySaver.go
configurationtypes/types.go
tests/mock.go

Update README
Tell that the distributed cache is supported in full version
Fix linter errors

fix: Linter and doc changes

---

README.md

There is still a few issue since I did not understand fully the meaning:
Line 49: 
if in the same network, use http://your-service, if not => use yourdomain.com
or if in the same network, use http://your-service, then access it through https://yourdomain
Line 132: Bad copy paste ? refresh doesn't seem to have parameters
Line 248: ??? No clue what does it mean
I'll edit them before the merging ;)

Fixing some english

---

plugins/caddy/Caddyfile
plugins/caddy/app.go
plugins/caddy/configuration.json
plugins/caddy/go.mod
plugins/caddy/go.sum
plugins/caddy/main.go

As we discussed with @francislavoie Souin must use the caddy App system instead of using a staticConfig variable to share default configuration.

Supports caddy App

---

plugins/base.go

Fix: Return stored status code when cache hit

---

cache/coalescing/requestCoalescing.go
cache/providers/abstractProvider.go
cache/providers/badgerProvider.go
cache/providers/embeddedOlricProvider.go
cache/providers/olricProvider.go
cache/types/layerStorage.go
cache/types/providers.go
cache/types/souin.go
plugins/base.go
plugins/caddy/app.go
plugins/caddy/go.mod
plugins/caddy/go.sum
plugins/caddy/main.go
rfc/bridge.go
rfc/standalone.go
rfc/transport.go
rfc/vary.go

feat: Replace VaryLayerStorage to plain storage system with algorithm

---

plugins/traefik/go.mod
plugins/traefik/go.sum
plugins/traefik/vendor/github.com/darkweak/souin/rfc/bridge.go
plugins/traefik/vendor/modules.txt
rfc/bridge.go

Use Routripper interface instead of custom function

---

README.md
plugins/souin/main.go

- Move first call into for
- Use TLS port from config

Use TLS port from config

---

.github/workflows/plugins-master.yml
README.md
plugins/caddy/go.mod
plugins/traefik/base.go
plugins/traefik/main.go

Fix a Træfik issue related to #144

fix(plugins): Traefik custom writer

---

docs/e2e/Souin E2E.postman_collection.json
plugins/caddy/Caddyfile
plugins/caddy/httpcache_test.go
plugins/traefik/vendor/github.com/darkweak/souin/rfc/cacheStatus.go
plugins/traefik/vendor/github.com/darkweak/souin/rfc/transport.go
rfc/cacheStatus.go
rfc/transport.go

fix(#176): obeying max-age directive in the response

---

cache/providers/badgerProvider.go
plugins/caddy/Caddyfile

Solve https://github.com/caddyserver/cache-handler/issues/21 from @ueffel

feat(provider): Badger singleton support multiple directives

---

plugins/base.go
plugins/caddy/Caddyfile
rfc/bridge.go

fix(issue-198): Support 304 response

---

README.md
plugins/caddy/go.mod
plugins/chi/go.mod
plugins/echo/go.mod
plugins/gin/go.mod
plugins/skipper/go.mod
plugins/traefik/base.go
plugins/traefik/go.mod
plugins/traefik/vendor/github.com/darkweak/souin/rfc/bridge.go
plugins/traefik/vendor/modules.txt
plugins/tyk/go.mod
plugins/webgo/go.mod

release(v1.6.5)

---

.github/workflows/plugins.yml
cache/providers/embeddedOlricProvider.go
docs/e2e/Souin E2E.postman_collection.json
plugins/caddy/Caddyfile
plugins/caddy/httpcache.go

Closes https://github.com/caddyserver/cache-handler/issues/26
Closes #211

fix(plugins): Manage Surrogate-Keys only with global in caddy

---

.github/workflows/plugins.yml
cache/providers/badgerProvider.go
cache/providers/embeddedOlricProvider.go
cache/providers/embeddedOlricProvider_test.go
cache/providers/olricProvider.go
cache/providers/olricProvider_test.go
cache/types/providers.go
plugins/caddy/app.go
plugins/caddy/cleaner.go
plugins/caddy/go.mod
plugins/caddy/httpcache.go
plugins/go-zero/examples/httpcache.go
plugins/traefik/override/providers/cacheProvider.go
plugins/traefik/vendor/github.com/darkweak/souin/LICENSE
plugins/traefik/vendor/github.com/darkweak/souin/cache/providers/cacheProvider.go
plugins/traefik/vendor/github.com/darkweak/souin/cache/types/providers.go
plugins/traefik/vendor/modules.txt
plugins/tyk/override/providers/cacheProvider.go

Closes https://github.com/caddyserver/cache-handler/issues/29

fix(plugins): Support caddy config reload for embedded olric

---

cache/providers/nutsProvider.go

Fix nutsdb regex based cache purge.

---

.github/workflows/plugins-master.yml
cache/providers/nutsProvider.go
cache/surrogate/providers/common.go
cache/surrogate/providers/common_test.go
cache/surrogate/providers/souin.go
cache/surrogate/providers/souin_test.go
context/key.go
plugins/caddy/cleaner.go
plugins/caddy/httpcache.go

fix(surrogate-keys): Not remove the Surrogate-Key header in Souin provider

---

.github/workflows/plugins.yml
.github/workflows/workflow_plugins_generator.sh
README.md
plugins/beego/go.mod
plugins/caddy/go.mod
plugins/caddy/httpcache.go
plugins/chi/go.mod
plugins/dotweb/go.mod
plugins/echo/go.mod
plugins/fiber/go.mod
plugins/gin/go.mod
plugins/go-zero/go.mod
plugins/goyave/go.mod
plugins/kratos/go.mod
plugins/roadrunner/go.mod
plugins/skipper/go.mod
plugins/traefik/go.mod
plugins/traefik/vendor/github.com/darkweak/souin/plugins/souin/configuration/configuration.yml
plugins/traefik/vendor/modules.txt
plugins/tyk/go.mod
plugins/webgo/go.mod

hotfix(plugins): Caddy default logger

---

plugins/caddy/httpcache.go

The `caddyfile.Unmarshaler` interface allows Souin to be loaded by a parent Caddy plugin.
Go tests are passing under `github.com/darkweak/souin/plugins/caddy`

Add caddyfile.Unmarshaler interface for Caddy plugin

---

README.md

Update Cache-Status RFC URL

---

cache/providers/etcdProvider.go
plugins/base.go

Fix https://github.com/caddyserver/cache-handler/issues/39

fix(chore): handle request cancellation

---

plugins/roadrunner/httpcache.go
plugins/roadrunner/httpcache_test.go

- Compatibility with the Endure v2 (https://github.com/roadrunner-server/endure)
- Endure v2 does not accept structures in the `Init` method anymore. This is in sync with the Go way of accepting interfaces and returning structures
- The Logger interface is implemented by the https://github.com/roadrunner-server/logger plugin and provided to all other plugins included in the standard RoadRunner bundle.
By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.
`[Author TODO: Meet these criteria.]`
`[Reviewer TODO: Verify that these criteria are met. Request changes if not]`

feature: compatibility with the endure v2

---

api/debug/debug.go
api/main.go
api/main_test.go
configurationtypes/types.go
plugins/base.go
plugins/beego/souin.go
plugins/caddy/configuration.go
plugins/kratos/configuration.go
plugins/souin/agnostic/configuration_parser.go

feat(chore): add pprof debug api endpoint

---

cache/providers/abstractProvider.go
cache/providers/abstractProvider_test.go
plugins/roadrunner/examples/Dockerfile.test
plugins/roadrunner/examples/configuration.toml
plugins/traefik/override/providers/abstractProvider.go
plugins/traefik/vendor/github.com/darkweak/souin/api/debug/debug.go
plugins/traefik/vendor/github.com/darkweak/souin/cache/providers/abstractProvider.go
plugins/traefik/vendor/github.com/darkweak/souin/configurationtypes/types.go
plugins/traefik/vendor/github.com/darkweak/souin/rfc/standalone.go
plugins/traefik/vendor/modules.txt
plugins/tyk/override/providers/abstractProvider.go
rfc/standalone.go

fix(chore): escape headers with colons

---

plugins/base.go
plugins/traefik/base.go
plugins/traefik/main.go

Closes #301 
Closes https://github.com/ueffel/caddy-imagefilter/issues/1

fix(plugins): api handlers on traefik

---

README.md
context/graphql.go
plugins/beego/go.mod
plugins/caddy/go.mod
plugins/chi/go.mod
plugins/dotweb/go.mod
plugins/echo/go.mod
plugins/fiber/go.mod
plugins/gin/go.mod
plugins/go-zero/go.mod
plugins/goyave/go.mod
plugins/kratos/go.mod
plugins/roadrunner/go.mod
plugins/skipper/go.mod
plugins/traefik/go.mod
plugins/traefik/override/context/graphql.go
plugins/traefik/vendor/github.com/darkweak/souin/context/graphql.go
plugins/traefik/vendor/modules.txt
plugins/tyk/go.mod
plugins/tyk/override/context/graphql.go
plugins/webgo/go.mod

fix(chore): request body consumed

---

context/key.go
plugins/caddy/configuration.json
plugins/caddy/httpcache.go
plugins/caddy/httpcache_test.go

Fixing https://github.com/darkweak/souin/issues/327

fix(plugin/caddy): handle disable_query directive

---

pkg/middleware/middleware.go
pkg/rfc/age.go
pkg/rfc/vary.go
plugins/caddy/httpcache.go
plugins/caddy/httpcache_test.go
plugins/souin/main.go

Closes https://github.com/caddyserver/cache-handler/issues/43
TBD before merge:

fix(chore): no more lowercase on varied values

---

plugins/gin/souin.go

fix(plugins): use base writer as ServeHTTP parameter

---

pkg/middleware/middleware.go
pkg/middleware/writer.go
plugins/gin/souin.go

fix(plugins): use base writer as ServeHTTP parameter (#341)

---

plugins/caddy/configuration.go

Fix parse panic with `cache:cdn:dynamic` option in `Caddyfile` config.
Add a panic message for non-global API block (which will be ignored) in Caddyfile.

fix(caddy): surrogate-related config parsing

---

plugins/traefik/override/storage/cacheProvider.go
plugins/traefik/override/surrogate/providers/common.go
plugins/traefik/vendor/github.com/darkweak/souin/api/souin.go
plugins/traefik/vendor/github.com/darkweak/souin/pkg/api/souin.go
plugins/traefik/vendor/github.com/darkweak/souin/pkg/storage/cacheProvider.go
plugins/traefik/vendor/github.com/darkweak/souin/pkg/surrogate/providers/common.go

fix(plugins): traefik surrogate-keys

---

plugins/roadrunner/README.md

chore: update README.md for RoadRunner to fit the latest `velox.toml` updates

---

README.md
plugins/beego/go.mod
plugins/caddy/dispatch.go
plugins/caddy/go.mod
plugins/caddy/httpcache.go
plugins/chi/go.mod
plugins/dotweb/go.mod
plugins/echo/go.mod
plugins/fiber/go.mod
plugins/gin/go.mod
plugins/go-zero/go.mod
plugins/goa/go.mod
plugins/goyave/go.mod
plugins/hertz/go.mod
plugins/kratos/go.mod
plugins/roadrunner/go.mod
plugins/skipper/go.mod
plugins/souin/go.mod
plugins/souin/storages/go.mod
plugins/traefik/go.mod
plugins/traefik/vendor/modules.txt
plugins/tyk/go.mod
plugins/webgo/go.mod

Closes https://github.com/caddyserver/cache-handler/issues/102

fix(chore): caddy default provider check
