Dockerfile-prod
Makefile

Ensure production container build

---

rfc/standalone.go

Otherwise things like `/shop`, `/shop?page=2`, `/shop?category_id=2`,
`/shop?product_id=42` and so on are all considered as the same resource.
Probably a more sophisticated solution is desired here, as this does not
take into account UTM parameters[1], for instance.
[1]: https://en.wikipedia.org/wiki/UTM_parameters

Use URL.RequestURI to construct a cache key

---

.github/workflows/release.yml

alpine image is not compiled for this arch

Remove linux/riscv64 from BuildX CI

---

Dockerfile-prod

Otherwise it'll always (cross) compile for linux/amd64 regardless of the current arch.
Ref. https://github.com/darkweak/souin/pull/143#issuecomment-947791410

Remove hardcoded GOOS and GOARCH env vars

---

README.md
plugins/traefik/base.go
plugins/traefik/main.go

Because the plugin configuration parsing is done differently in TraefikEE and Traefik Proxy, the configuration object given to the souin plugin is respectively different. This is why the code to parse this object was only working in the TraefikCE case.
Therefore, this pull request fixes the parsing in the souin plugin to work for both kinds of input.
Fixes #163

Fix panic when parsing slice of string in Traefik plugin

---

plugins/traefik/vendor/github.com/darkweak/souin/rfc/bridge.go
plugins/traefik/vendor/github.com/darkweak/souin/rfc/standalone.go
rfc/bridge.go
rfc/standalone.go
rfc/standalone_test.go

Should fix #169 by adding a check for status code in the `canStore` function of `rfc/standalone.go`
Note: If this feature not necessarily desired, one could add a parameter to the configuration file to disable it

Fixes  #169

---

README.md
cache/types/souin.go
configurationtypes/types.go
plugins/base.go
plugins/caddy/Caddyfile
plugins/caddy/README.md
plugins/caddy/configuration.go
plugins/caddy/examples/Caddyfile-embedded-olric
plugins/caddy/examples/Caddyfile-file-configuration-olric
plugins/caddy/examples/Caddyfile-not-distributed
plugins/caddy/examples/Caddyfile-remote-olric-cluster
plugins/caddy/examples/configuration-embedded-olric.json
plugins/caddy/examples/configuration-file-configuration-olric.json
plugins/caddy/examples/configuration-not-distributed.json
plugins/caddy/examples/configuration-remote-olric-cluster.json
plugins/caddy/httpcache.go
plugins/traefik/main.go
plugins/traefik/souin-configuration.yaml
plugins/traefik/vendor/github.com/darkweak/souin/cache/types/souin.go
plugins/traefik/vendor/github.com/darkweak/souin/configurationtypes/types.go
plugins/traefik/vendor/github.com/darkweak/souin/rfc/bridge.go
plugins/tyk/configuration.go
rfc/bridge.go

When the upstream returns a response without `Cache-Control` header set, Souin caches it with the configured max-TTL (https://github.com/darkweak/souin/issues/176#issuecomment-1023591184). The behavior is acceptable according to [RFC 7324](https://httpwg.org/specs/rfc7234.html#:~:text=Therefore%2C%20origin%20servers%20are%20encouraged%20to%20send%20explicit%20directives).
But sometimes the upstream services expect those responses to be not cached. So I involved an option `default_cache_control` for `default_cache` and `url.*`:
```yaml
default_cache:
ttl: 86400s
default_cache_control: no-store # Disable cache for responses without a Cache-Control header
```

feat(core): specify default Cache-Control for responses when not set by upstream

---

plugins/base.go
plugins/traefik/base.go
plugins/traefik/vendor/github.com/darkweak/souin/rfc/bridge.go
rfc/bridge.go

fix(#178): Drop non Get/HEAD HTTP method

---

.github/workflows/non-regression.yml
.github/workflows/plugins-master.yml
.github/workflows/plugins.yml

This enables lint/e2e tests to run on each push of pull requests. Useful for #177.

ci: run tests for pull requests

---

README.md
api/souin.go

If specified only lists or purges cache entries that match the given
regular expression. If not specified, lists all and purges all cache.
If i've read correctly you are currently working on getting surrogate keys working properly.
I don't wish to step on your toes, it just seemed more logical to me to be able to list and purge cache contents selectively this way. If you think it's ok, please merge.

Fix cache cleaning and add proper cache listing based on regexes.

---

plugins/caddy/httpcache.go

In case of responses that have no body, headers are incorrectly received from caddy after the first round trip. This can cause some responses to be incorrectly cached.
This little fix copies the missing headers in the proper place.

Redirect headers breakage

---

README.md
api/souin.go
api/souin_test.go
cache/surrogate/providers/types.go
configuration/configuration.sample.yml
configurationtypes/types.go
context/timeout.go
context/timeout_test.go
context/types.go
plugins/base.go
plugins/beego/souin.go
plugins/caddy/Caddyfile
plugins/caddy/README.md
plugins/caddy/configuration.go
plugins/caddy/httpcache.go
plugins/kratos/configuration.go
plugins/roadrunner/README.md
plugins/roadrunner/configuration.go
plugins/traefik/base.go
plugins/traefik/main.go
plugins/traefik/override/context/timeout.go
plugins/traefik/override/context/types.go
plugins/traefik/override/surrogate/providers/common.go
plugins/traefik/vendor/github.com/darkweak/souin/api/souin.go
plugins/traefik/vendor/github.com/darkweak/souin/cache/surrogate/providers/common.go
plugins/traefik/vendor/github.com/darkweak/souin/cache/surrogate/providers/types.go
plugins/traefik/vendor/github.com/darkweak/souin/configurationtypes/types.go
plugins/traefik/vendor/github.com/darkweak/souin/context/timeout.go
plugins/traefik/vendor/github.com/darkweak/souin/context/types.go
plugins/tyk/configuration.go

feat(core): Configurable timeout on backend and cache access

---

plugins/roadrunner/configuration.go
plugins/roadrunner/go.mod
plugins/roadrunner/go.sum
plugins/roadrunner/httpcache.go
plugins/roadrunner/httpcache_test.go

- RR container (endure) may detect plugins that implement a particular interface. Thus there is no need to depend on `api` anymore, the interface might be declared in the plugin (where it actually used, Go-way 😄).
- Remove `roadrunner-server/api` dep.
- Update error handling in the tests.
- Declare the local interface:
```go
// Configurer interface used to parse yaml configuration.
// Implementation will be provided by the RoadRunner automatically via Init method.
type Configurer interface {
// Get used to get config section
Get(name string) any
// Has checks if config section exists.
Has(name string) bool
}
```
If you need another (additional) method, just check the structure `Plugin` (as the implementation): https://github.com/roadrunner-server/config/blob/master/plugin.go, and add the …

feat: remove dep on `roadrunner-server/api`

---

README.md
plugins/traefik/main.go

fix(plugins): traefik configuration parsing

---

README.md
configurationtypes/types.go
context/key.go
context/key_test.go
context/types_test.go
plugins/caddy/configuration.go
plugins/kratos/configuration.go
plugins/souin/agnostic/configuration_parser.go

Adds the parameter "disable_query", which disable the use of query string in cache key name.

Disable query string in key

---

plugins/traefik/main.go

In the Traefik plugin, the `default_cache.mode` parameter was not being read, so Souin was always running in **strict** mode.

fix(traefik): parse "mode" configuration parameter in Traefik plugin

---

pkg/rfc/age.go
pkg/rfc/cache_status.go

Fixes following test from [cache-tests.fyi](https://cache-tests.fyi): `freshness-max-age-age`, [freshness-max-age-s-maxage-shared-longer-multiple](url). Unlocks the whole "Age Parsing" section of the test suite (see [here](https://cache-tests.fyi/#age-parse)).

fix(rfc): Age header update

---

pkg/middleware/middleware.go
pkg/rfc/vary.go

Add support for `Vary` header with `*` (star) value.
Related tests from [cache-tests.fyi](https://cache-tests.fyi):
- `vary-star`
- All tests in the "[Vary Parsing](http://localhost:8000/#vary-parse)" section

fix(rfc): Add support for Vary star

---

pkg/middleware/middleware.go

Proposal for a fix for the incorrect panic with `singleflight.panicError` when `http.ErrAbortHandler` in expected by `net/http` (see [here](https://github.com/golang/go/blob/8db131082d08e497fd8e9383d0ff7715e1bef478/src/net/http/server.go#L1895)) and `http2` (see [here](https://github.com/golang/net/blob/689bbc7005f6bbf9fac1a8333bf03436fa4b4b2a/http2/server.go#L2358)).
References:
- `http.ErrAbortHandler` panic is triggered by Caddy [here](https://github.com/caddyserver/caddy/blob/cb86319bd50322d4ac9e730b2fc5639daa24b82a/modules/caddyhttp/reverseproxy/reverseproxy.go#L974C3-L974C30).

fix(chore): Wrong panic in singleflight

---

pkg/middleware/middleware.go

Related to [cache-test.fyi](https://cache-tests.fyi/#heuristic): `heuristic-502-not_cached`, `heuristic-503-not_cached`, `heuristic-504-not_cached`.
At the end of ServeHTTP, if Upstream returns a `upstreamError` error, the error is returned (e.g., to Caddy) and the server will with `500 Internal server error`. Instead, the upstream error should be sent back 50x errors to the client.

fix(chore): Send upstream 50x error instead of failing

---

.github/workflows/plugin_template.yml
.github/workflows/plugins.yml
.github/workflows/workflow_plugins_generator.sh

I was watching the Actions run on the PRs and noticed it's hard to read the Action name due to how long the name of the action as it includes the description in addition to the plugin name. This should make it better.

ci: improve action name for readability

---

pkg/api/souin.go

After providing some testing of removing keys by regex from Redis storage using Souin API, I saw that keys still exist, and nothing happened after calling the `PURGE` request with regex. But the `PURGE` request to the `/flush` endpoint works.
So I debugged the purge method and found that it deleted keys only by providing a whole key ID. So I added checking if the key is the regex than`Delete` method in Souin API should call `DeleteMany` instead of `Delete.`
Related to #417

fix(chore): allow to delete keys by regex

---

pkg/middleware/writer.go

Fix https://github.com/caddyserver/cache-handler/issues/104
Tested with
```
FROM caddy:2.8.4-builder AS builder
RUN xcaddy build --with github.com/darkweak/souin=github.com/imlonghao/souin@fix-empty-response --with github.com/darkweak/souin/plugins/caddy
FROM caddy:2.8.4
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

fix(middleware): avoid sending empty Content-Length

---

plugins/caddy/configuration.go

Some options for CDN cannot be set from caddy directives due to some missing mapping/configuration.
This pull request adds a directive for each that is missing and documented - so is a fix.
Thanks for al your work!
Ps the first lines of Go I've every written.

Add missing configuration options to cdn directive

---

pkg/middleware/middleware.go
pkg/middleware/writer.go
plugins/traefik/override/middleware/middleware.go
plugins/traefik/override/middleware/writer.go
plugins/traefik/vendor/github.com/darkweak/souin/pkg/middleware/middleware.go
plugins/traefik/vendor/github.com/darkweak/souin/pkg/middleware/writer.go

fix(writer): buffer race condition

---

pkg/middleware/middleware.go
pkg/middleware/writer.go
pkg/surrogate/providers/common.go
pkg/surrogate/providers/common_test.go
plugins/traefik/override/middleware/writer.go
plugins/traefik/override/surrogate/providers/common.go
plugins/traefik/vendor/github.com/darkweak/souin/pkg/middleware/writer.go
plugins/traefik/vendor/github.com/darkweak/souin/pkg/surrogate/providers/common.go
plugins/tyk/override/cache/surrogate/providers/common.go

Add the ability to the upstream to select its own storage using the HTTP response header `X-Souin-Storer`.  
e.g. `X-Souin-Storer: otter`.

feat(core): upstream select it's own storage

---

context/now.go
pkg/middleware/middleware.go
pkg/surrogate/providers/common.go
plugins/caddy/admin.go
plugins/caddy/app.go
plugins/caddy/httpcache_test.go

Closes #584 
Closes #583 
Closes #588 
Closes #585 
Cache-handler:
Closes https://github.com/caddyserver/cache-handler/issues/116
Closes https://github.com/caddyserver/cache-handler/issues/118
Storages:
Closes https://github.com/darkweak/storages/issues/23

fix(multiple): december 2024 wave

---

pkg/middleware/middleware.go

related: https://github.com/caddyserver/cache-handler/issues/112#issuecomment-3159754093
TLDR: I'm getting `UPSTREAM-ERROR-OR-EMPTY-RESPONSE` for all HEAD requests even though I've included HEAD in `allowed_http_verbs` configuration.
```caddyfile
{
cache {
log_level DEBUG
badger
allowed_http_verbs GET HEAD
default_cache_control public
}
log {
level DEBUG
}
}
http://localhost:3000 {
cache {
ttl 10s
}
respond "hello world" 200
}
```
After the fix:
```console
$ curl --head http://localhost:3000/
HTTP/1.1 200 OK
Cache-Control: public
Cache-Status: Souin; fwd=uri-miss; stored; key=HEAD-http-localhost:3000-/
Content-Length: 11
Content-Type: text/plain; charset=utf-8
Server: Caddy
Date: Wed, 06 Aug 2025 12:23:25 GMT
$ curl --head http://localhost:3000/
HTTP/1.1 200 OK
Age: 1
Cache-Control: …
```

fix(storage): head requests not cached

---

pkg/storage/defaultProvider.go
plugins/caddy/httpcache.go

Fixes:
1. DefaultProvider DeleteMany using the incorrect key (used regex instead of key)
~~2. disable_coalescing directive not being passed in configuration~~

DefaultProvider DeleteMany key fix
